nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P04.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P04.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P06.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P06.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P08.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P08.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P10.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P10.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P11.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P11.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P13.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P13.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P16.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P16.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P17.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P17.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P19.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P19.log &
nohup ./teco-spruce.exe conf_opt_each_treat/teco_conf_P20.nml > /Users/jianzhou/MyDocs/case_GPPmax_CUP/TECO_outputs/outlogs/out_alltreat_P20.log &